dataloader:
  clip_frames: 4
  sampling_rate: 1
  num_random_loader_workers: 4
  num_sequential_loader_workers: 4

scheduler:
  type: StepLR
  step_size: 15
  gamma: 0.1

optimizer:
  type: AdamW
  learning_rate: 0.00001
  weight_decay: 0.0001
